# Solutions to U(1) anomaly equations

**Nicole Rivera**
Para el curso de computación avanzada

Se implementará una primera solución a bajos n del método propuesto por Costa y colaboradores para encontrar soluciones quirales a las ecuaciones

$$ z_1^{3} + \dots + z_n^{3} = 0 $$

$$ z_1 + \dots + z_n = 0 $$

Basado en el articulo https://doi.org/10.1103/PhysRevLett.123.151601

In [1]:
import numpy as np

In [2]:
def merge_op(x, y):
    """ merge operation for z with specified x, y"""
    return np.sum( x*(y**2) )*x - np.sum( (x**2) * y )*y 

def even(n):
    """ even sized U1 solution calculator"""
    
    m = int(n/2 - 1) # k, l size 

    k = np.random.randint(1, 10, size=m)
    l = np.random.randint(1, 10, size=m)
    
    # generate plus and minus vector 
    vp = np.concatenate(([l[0]], k, [-l[0]], -k))
    vm = np.concatenate(([0,0], l, -l))
    
    # calculate z
    z = merge_op(vp, vm)
    
    return z

def odd(n):
    """ odd sized U1 solution calculator"""
    
    m = int((n - 3)/2) # k, l size
    
    k = np.random.randint(1, 10, size=m+1)
    l = np.random.randint(1, 10, size=m)
    
    # generate plus and minus vector 
    up = np.concatenate(([0], k, -k))
    um = np.concatenate((l, [k[0], 0], -l, [-k[0]]))
    
    # calculate z
    z = merge_op(up, um)
    
    return z

def no_vectorlike(z):
    """ classifies if z is vector-like or quiral solution """
    
    # gets unique values of z and its absolute value elemets
    uniq_abs = np.unique(np.abs(z)).shape[0]
    uniq_all = np.unique(z).shape[0]
    
    if uniq_abs == uniq_all:
        # if unique values are equal to absolute unique values the z is quiral
        return 1
    else:
        # otherwise is vector-like
        return 0

def prueba_U1(q):
    """ proof operations of U1 group """
    
    a3 = np.sum(q**3)
    a1 = np.sum(q)
    
    return (a3, a1)

### ---- Funcion principal ----###
def joint(n0):
    """ main function to calculate quiral U1 solutions """
    
    rs = 0 # aceptance variable - 0 is no-quiral, 1 is quiral
    
    while rs == 0: 
        
        # gets z according to case
        if n0%2 == 0 and n0 > 2:
            zf = even(n0)
        elif n0%2 != 0 and n0 >= 5:
            zf = odd(n0)
        else:
            print("ingrese entero positivo válido")
            rs = 2 
            break
            
        div = np.gcd.reduce(zf) # finds z greater common divisor
    
        rs = no_vectorlike(zf) # evaluates if z is vector-like
        
        # evaluates other conditions over z
        if rs  == 1:
            zn = zf/div # reduced z by its gcd
            if np.any(np.abs(zn)>30) or np.any(np.abs(zn) == 0):
                # all elements must be non zero and minor than 30
                rs = 0
                continue
            else:
                return (zn, div) #use this if you also need gcd information
                #return zn # use this if you only need z 
                break

In [3]:
print("solución, divisor")
joint(7)

solución, divisor


(array([ -3., -26., -16., -12.,  24.,  14.,  19.]), 4)

In [4]:
for i in range(0, 100):
    print(joint(6))

(array([ -8.,  -1., -24.,  -3.,  23.,  13.]), 96)
(array([ -5., -15.,  13.,  11.,  -3.,  -1.]), 36)
(array([-18.,  -9., -26.,  20.,   8.,  25.]), 8)
(array([ -4.,  -5., -17.,  -1.,  15.,  12.]), 12)
(array([  6.,   3., -13., -17.,  19.,   2.]), 81)
(array([-11., -11., -19.,  16.,   8.,  17.]), 54)
(array([ -7.,  -7., -17.,  15.,   3.,  13.]), 32)
(array([-1., -9.,  4., 11.,  4., -9.]), 16)
(array([ -3., -24., -16.,  25.,  13.,   5.]), 13)
(array([-2., -6., -3.,  5.,  5.,  1.]), 1134)
(array([ -3., -24.,  -2.,  19.,  20., -10.]), 18)
(array([ -5.,  -1., -23.,  -7.,  21.,  15.]), 22)
(array([  8.,   3., -12., -10.,  13.,  -2.]), 52)
(array([  6.,   3.,   2., -17.,  19., -13.]), 6)
(array([-21., -21.,   1.,  26.,   6.,   9.]), 2)
(array([ -3., -24.,  -2.,  19.,  20., -10.]), 18)
(array([-10.,  -5., -11.,   8.,   6.,  12.]), 192)
(array([  8.,   2., -22., -23.,  28.,   7.]), 8)
(array([-12., -15.,  10.,  16.,  -1.,   2.]), 18)
(array([-11., -22., -10.,  15.,  21.,   7.]), 48)
(array([  7.,