# Solutions to U(1) anomaly equations

**Nicole Rivera**
Para el curso de computación avanzada

Se implementará una primera solución a bajos n del método propuesto por Costa y colaboradores para encontrar soluciones quirales a las ecuaciones

$$ z_1^{3} + \dots + z_n^{3} = 0 $$

$$ z_1 + \dots + z_n = 0 $$

Basado en el articulo https://doi.org/10.1103/PhysRevLett.123.151601

In [1]:
import numpy as np

In [2]:
def merge_op(x, y):
    return np.sum( x*(y**2) )*x - np.sum( (x**2) * y )*y 

def even(n):
    
    m = int(n/2 - 1) 

    k = np.random.randint(1, 10, size=m)
    l = np.random.randint(1, 10, size=m)

    vp = np.concatenate(([l[0]], k, [-l[0]], -k))
    vm = np.concatenate(([0,0], l, -l))
    
    z = merge_op(vp, vm)
    
    return z

def odd(n):
    
    m = int((n - 3)/2)
    
    k = np.random.randint(1, 10, size=m+1)
    l = np.random.randint(1, 10, size=m)
    
    up = np.concatenate(([0], k, -k))
    um = np.concatenate((l, [k[0], 0], -l, [-k[0]]))
    
    z = merge_op(up, um)
    
    return z

def no_vectorlike(z):
    
    uniq_abs = np.unique(np.abs(z)).shape[0]
    uniq_all = np.unique(z).shape[0]
    
    if uniq_abs == uniq_all:
        #print("quiral solution")
        return 1
    else:
        #print("vector-like solution")
        return 0

def prueba_U1(q):
    
    a3 = np.sum(q**3)
    a1 = np.sum(q)
    
    return (a3, a1)

### ---- Funcion principal ----###
def main(n0):
    
    rs = 0
    while rs == 0:
    
        if n0%2 == 0 and n0 > 2:
            zf = even(n0)
        elif n0%2 != 0 and n0 >= 5:
            zf = odd(n0)
        else:
            print("ingrese entero positivo válido")
            rs = 2 
            break
            
        div = np.gcd.reduce(zf)
    
        rs = no_vectorlike(zf)
        
        if rs  == 1:
            zn = zf/div
            if np.any(np.abs(zn)>30):
                #print("mayor que 30")
                rs = 0
                continue
            else:
                #print("menor que 30")
                return (zn, div)
                break

In [3]:
print("solución, divisor")
main(7)

solución, divisor


(array([ 12.,  21., -26., -11.,  21., -10.,  -7.]), 6)

In [4]:
for i in range(0, 100):
    print(main(6))

(array([-21., -21.,   1.,  26.,   6.,   9.]), 2)
(array([  5.,   4., -10.,  -8.,  11.,  -2.]), 15)
(array([ -3., -24.,   5.,  25.,  13., -16.]), 6)
(array([ -6., -21.,  -1.,  19.,  -5.,  14.]), 1)
(array([-3., -6., -2.,  5.,  5.,  1.]), 3)
(array([ -2.,  -2., -13.,  -3.,  12.,   8.]), 81)
(array([ -9.,  -7., -18.,   4.,  16.,  14.]), 288)
(array([ -8., -12.,   2.,  13.,   2.,   3.]), 32)
(array([-15., -12., -20.,  11.,  17.,  19.]), 45)
(array([ -3.,  -1., -15.,  -5.,  13.,  11.]), 6)
(array([ -5.,  -3., -15.,  -1.,  13.,  11.]), 40)
(array([ 16.,  14., -24., -21.,  26., -11.]), 24)
(array([-14., -21.,  -6.,  16.,  20.,   5.]), 8)
(array([ -3., -24.,  -2.,  19.,  20., -10.]), 18)
(array([ -7., -28.,  -5.,  25.,  19.,  -4.]), 2)
(array([ -7., -21.,  12.,  20.,  -5.,   1.]), 4)
(array([ -3.,  -8.,  12.,  10., -13.,   2.]), 3)
(array([ -2.,  -2., -13.,  -3.,  12.,   8.]), 16)
(array([-10., -20.,  -4.,  13.,  19.,   2.]), 24)
(array([-10., -20.,  -1.,  17.,  16.,  -2.]), 156)
(array([-3., 